### ISSUE TITLE
Trying to present the presentation controller while transitioning already.

### ISSUE THREAD

**Issue by Akree** [TinkoffCreditSystems/AcquiringSdk_IOS#1]
Добрый день.

При вызове presentPaymentView при нажатии на поле e-mail или поле для ввода данных карты клавиатура не открывается и полностью пропадает данный экран с последующей ошибкой:
```console
[Assert] Trying to present the presentation controller while transitioning already. (<TinkoffASDKUI.PullUpPresentationController: 0x7f94366895f0>)
```
AcquiringViewConfigration используется как в примере.
Также смущает порядок отображения полей.

<img src="https://user-images.githubusercontent.com/48877932/88158174-e6754700-cc35-11ea-830e-aae468879ad0.png" width ="350">

**Comment by Akree** [comment]
Это происходит тут: 
`TinkoffASDKUI/PopUpViewController#pushToNavigationStackAndActivate(204)`
>226 строка
```swift
dismiss(animated: false) {
  parentViewController.present(self, animated: false) {
    completion?()
  }
}
```

Опыта в iOS разработке у меня мало, но если я меняю эти строки на 
```swift
if textField != nil {
  textField!.becomeFirstResponder()
} else {
  dismiss(animated: false) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
      completion?()
    }
  }
}
```
то все работает почти как надо, за исключением размера экрана.
<img src="https://user-images.githubusercontent.com/48877932/88524730-ec976900-d023-11ea-820e-368090d374f3.jpg" width = 350>

И, также, этот экран не получается смахнуть вниз, чтобы закрыть. Он смахивается только вверх и появляется такая же ошибка как и при выделении тестовых полей. 

Подскажите, может просто я что-то не так делаю?)

**Comment by slavabuv** [comment]
доработали анимации для открытия и закрытия окна, в 2.0.1 ошибка не воспроизводится.

**Comment by Akree** [comment]
Здраствуйте, в 2.0.1 данная ошибка все также воспроизводится 😿
> При вызове presentPaymentView при нажатии на поле e-mail или поле для ввода данных карты клавиатура не открывается и полностью пропадает данный экран с последующей ошибкой:
> ```console 
> [Assert] Trying to present the presentation controller while transitioning already. (<TinkoffASDKUI.PullUpPresentationController: 0x7f94366895f0>)
> ```
При смахивании данного экрана вверх, появляется аналогичная ошибка...

**Comment by slavabuv** [comment]
Разобрался, некорректно работает сценарий когда окно показывается на UIViewController у которого нет navigationController, те он не в навигационном стеке. Доработаем!
