### ISSUE TITLE
В форме оплаты не проходит валидацию поле даты у сохраненной карты

### ISSUE THREAD

**Issue by Tetraquark** [TinkoffCreditSystems/AcquiringSdk_IOS#10]
Наткнулись на проблему - у сохраненной карты (с которой уже оплатили) почему то не проходит валидация у поля с датой (expire date).

Как воспроизводится:
1. Выполнить оплату с новой картой (после чего данные карты сохраняются).
2. Открыть оплату для следующей покупки (автоматически подставляются данные ранее сохраненной карты)
3. Нажать кнопку оплаты

После нажатия на кнопку оплаты красной полоской подчеркивается поле с датой и оплата не выполняется. Но оплата работает если эту же карту заново начать добавлять как новую.

<img width="383" alt="tinkoff_sdk_ios_expiredate" src="https://user-images.githubusercontent.com/7954933/96839074-e114dc00-1472-11eb-8a35-2526f8d60627.png">

**Comment by MaryAPc** [comment]
Здравствуйте! Скажите пожалуйста, какая версия SDK используется, версия OS и при каком типе платежа появляется эта ошибка - рекуррентный или нет

**Comment by Tetraquark** [comment]
Проверялось на симуляторе. 

- Версия SDK: 2.1.0
- Версия OS:  iOS 11.0
- Не рекуррентный платеж

**Comment by MaryAPc** [comment]
Спасибо, будем разбираться

**Comment by Megaman63** [comment]
У меня с рекурентным тоже самое.

**Comment by grishamsc** [comment]
@Tetraquark @Megaman63 
исправлено в версии 2.1.3 🙂
