### ISSUE TITLE
Расхождения в коде у сущности TinkoffASDKCore.Item

### ISSUE THREAD

**Issue by Megaman63** [TinkoffCreditSystems/AcquiringSdk_IOS#11]
Привет

Комменты к коду TinkoffASDKCore.Item говорят что нужно класть amount и price в копейках (кстати чем они отличаются):
<img width="566" alt="Screenshot 2020-10-24 at 19 53 31" src="https://user-images.githubusercontent.com/10582641/97086218-f7699600-1632-11eb-9dc2-be8001a2c246.png">

Но в init есть умножение на 100, в результате чего при совершении платежа возвращается ошибка что суммы не совпадают
<img width="758" alt="Screenshot 2020-10-24 at 19 53 22" src="https://user-images.githubusercontent.com/10582641/97086197-e7ea4d00-1632-11eb-89f2-f14608b372a1.png">

**Comment by MaryAPc** [comment]
Здравствйте! Здесь price это цена товара (объект Item), а amount общая сумма указанного кол-ва (quantity) товаров, допустим Item 1 - price 1000, amount 1000, quantity 1, Item 2 - price 1500, amount 3000, quantity 2. 
А amount в PaymentInitData тогда должен быть равен суммам amount товаров Item, т.е 4000.

В методе init на скриншоте ожидаются параметры в рублях. Мы исправим метод, чтобы это стало более очевидно

**Comment by Megaman63** [comment]
Спасибо!

**Comment by grishamsc** [comment]
@Megaman63 
в версии 2.1.5 добавлен метод инициализации структуры Item, принимающий price и amount в копейках.
