### ISSUE TITLE
Запрос FinishAuthorize отваливается по таймауту

### ISSUE THREAD

**Issue by Megaman63** [TinkoffCreditSystems/AcquiringSdk_IOS#12]
При добавлении карты отваливается по таймауту  запрос 🛫 Start POST request: https://securepay.tinkoff.ru/v2/FinishAuthorize если передать savingAsParentPayment как true.

Причем на почту приходит письмо что оплата прошла, и в итоге карта добавляется

Версия SDK 2.1.0, iOS 14.2

**Comment by MaryAPc** [comment]
Повторяется ли проблема, если проводить такую же операцию на тестовом контуре?

**Comment by Megaman63** [comment]
Это на тестовом контуре. На проде вроде все более менее быстро проходит. 
Если передать savingAsParentPayment = false, то как правило успевает отработать запрос до таймаута, но тоже не всегда

**Comment by MaryAPc** [comment]
Просто этот урл https://securepay.tinkoff.ru/v2/FinishAuthorize это прод контур, поэтому уточнила. Мы поищем проблему с таймаутом

**Comment by Megaman63** [comment]
А, я наверно путаю понятия. Контур - это сервер в AcquiringSdkConfiguration
<img width="671" alt="Screenshot 2020-10-26 at 15 36 24" src="https://user-images.githubusercontent.com/10582641/97167929-14bc7280-17a1-11eb-9513-30336e006d70.png">

Да, я действительно хожу на прод, так как работающие терминалы есть только там
В ответе я имел в виду терминалы - демо терминал отваливается по таймауту, прод терминал вроде шустро отрабатывает

**Comment by MaryAPc** [comment]
Поняла вас, посмотрим

**Comment by grishamsc** [comment]
@Megaman63 
должно починиться в версии в версии 2.1.3 🙂
