### ISSUE TITLE
Проблемы при инициализации платежа

### ISSUE THREAD

**Issue by abpopov** [TinkoffCreditSystems/AcquiringSdk_IOS#13]
Здравствуйте

Подскажите пожалуйста

получаем в логи такую ошибку 

{"Success":false,"ErrorCode":"7","Message":"Неверный статус покупателя.","Details":"Покупатель не найден.","CustomerKey":"номер телефона"}

По какой причине она появляется?

**Comment by MaryAPc** [comment]
Здравствуйте! Такая ошибка приходит в ответе на запрос GetCardList, она означает, что customer key ещё не был зарегистрирован в системе. Как только покупать с заданными customer key совершит первую покупку, система его зарегистрирует и ошибка не будет приходить для данного customer key

**Comment by abpopov** [comment]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/2630565/97316853-41dd5380-187b-11eb-9f1a-f2163014c805.png">
Но при этом наблюдаем такое на устройстве

**Comment by MaryAPc** [comment]
Кроме ошибки "Покупатель не найден.", в логах других ошибок больше нет, системных может быть? Также укажите пожалуйтса версию OS, на которой не загружается экран оплаты

**Comment by abpopov** [comment]
1) Попробовали с теми же данными на андройде  - доходит до ввода номера карты  потом ошибка (разработчик говорит что возвращается ошибка неверный номер карты)
2) теперь на iOS нет никаких ошибок, похоже что по причине того что на андройде пробовали 
3) теперь просто висит экран как на скрине

**Comment by abpopov** [comment]
В андройде получаем такую ошибку {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Неверный номер карты"}

**Comment by MaryAPc** [comment]
Висит экран сразу после его открытия или после попытки оплатить?

**Comment by abpopov** [comment]
после открытия 
До ввода данных не доходит

**Comment by MaryAPc** [comment]
Можете скинуть какие сейчас есть логи на iOS?

**Comment by abpopov** [comment]
Сейчас никаких

**Comment by MaryAPc** [comment]
SDK логи включены? Нет даже такого лога при открытии экрана?
`Start POST request: https://securepay.tinkoff.ru/v2/GetCardList, with paramaters: ....`

**Comment by abpopov** [comment]
ASDK ->]: on main thread, in NetworkTransport.swift, func createRequest(for:), at line: 92 do:
🛫 Start POST request: https://securepay.tinkoff.ru/v2/GetCardList, with paramaters: ["CustomerKey":, "TerminalKey": "", "Token": ""]
[ASDK ->]: on <NSThread: 0x600003ae3100>{number = 9, name = (null)}, in NetworkTransport.swift, func send(operation:responseDelegate:completionHandler:), at line: 229 do:
🛬 End request: https://securepay.tinkoff.ru/v2/GetCardList, with response data:
{"Success":false,"ErrorCode":"7","Message":"Неверный статус покупателя.","Details":"Покупатель не найден.","CustomerKey":" "}

**Comment by abpopov** [comment]
На андройде получаем следующую ошибку  {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Неверный номер карты"}

**Comment by MaryAPc** [comment]
Будем разбираться что не так

**Comment by razorkoo** [comment]
Столкнулись со схожей проблемой. Запросы проходят, но модальное окно все равно не загружается, бесконечно висит UIActivityIndicator.
Данные из логов (Token, TerminalKey, Pan были удалены), также Token, TerminalKey, CustomerKey были взяты из демопроекта. 
`🛫 Start POST request: https://rest-api-test.tcsbank.ru/v2/GetCardList, with paramaters: ["CustomerKey": TestSDK_CustomerKey1, "Token": "", "TerminalKey": ""]

🛬 End request: https://rest-api-test.tcsbank.ru/v2/GetCardList, with response data:
[{"CardId":"70000002211","Pan":"","Status":"A","RebillId":"700000062147","CardType":0,"ExpDate":"1122"},{"CardId":"70000002212","Pan":"","Status":"D","RebillId":"","CardType":0,"ExpDate":"1144"},{"CardId":"70000002213","Pan":"","Status":"D","RebillId":"","CardType":0,"ExpDate":"1222"},{"CardId":"70000002537","Pan":"","Status":"A","RebillId":"","CardType":0,"ExpDate":"1122"},{"CardId":"70000001381","Pan":"","Status":"D","RebillId":"","CardType":0,"ExpDate":"1222"},{"CardId":"70000001379","Pan":"","Status":"D","RebillId":"","CardType":0,"ExpDate":"1231"},{"CardId":"70000000485","Pan":"","Status":"D","RebillId":"700000026098","CardType":0,"ExpDate":"1122"}]

🛫 Start POST request: https://rest-api-test.tcsbank.ru/v2/Init, with paramaters: ["CustomerKey": TestSDK_CustomerKey1, "TerminalKey": "", "Token": "", "Amount": 100, "OrderId": 3264500]

🛬 End request: https://rest-api-test.tcsbank.ru/v2/Init, with response data:
{"Success":true,"ErrorCode":"0","TerminalKey":"","Status":"NEW","PaymentId":"700000478360","OrderId":"3264500","Amount":100}`

**Comment by vdugnist** [comment]
Как раз сегодня это дебажил. В моём случае объект AcquiringUISDK уходил из скоупа и уничтожался.

**Comment by abpopov** [comment]
> Как раз сегодня это дебажил. В моём случае объект AcquiringUISDK уходил из области видимости и уничтожался.

На это помогло не сильно)

sdk не должно быть локальным

Но теперь получаем следующее 


[ASDK ->]: on <NSThread: 0x600003e6b9c0>{number = 15, name = (null)}, in NetworkTransport.swift, func send(operation:responseDelegate:completionHandler:), at line: 229 do:
🛬 End request: https://securepay.tinkoff.ru/v2/Check3dsVersion, with response data:
{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Неверный номер карты"}
failure(Error Domain=Неверные параметры. Неверный номер карты Code=9999 "(null)" UserInfo={ErrorCode=9999, Success=false, TerminalKey=null, Details=Неверный номер карты, Message=Неверные параметры.})

**Comment by MaryAPc** [comment]
@abpopov при этом данные карты вводили правильно и карта не с истекшим сроком?

**Comment by abpopov** [comment]
Да точно  правильные карта Сбера

**Comment by MaryAPc** [comment]
можете прислать paymentId операции с такой ошибкой? посмотрим почему отклоняется

**Comment by abpopov** [comment]
PaymentId":"350706322"

**Comment by MaryAPc** [comment]
@abpopov был установлен в ЛК универсальный тип подключения, исправили на тип мобильные платежи. попробуйте повторить попытку оплаты

**Comment by abpopov** [comment]
> @abpopov был установлен в ЛК универсальный тип подключения, исправили на тип мобильные платежи. попробуйте повторить попытку оплаты

Сделайте что выработало и универсальное и сдк

У нас теперь на сайте не работают платежи

**Comment by MaryAPc** [comment]
@abpopov коллеги сообщили, что в вашем случае необходимо 2 терминала - один для обычных платежей с универсальным подключением и второй для мобильных платежей. Вам нужно будет обратиться в нашу поддержку для создания доп терминала

**Comment by grishamsc** [comment]
@abpopov @razorkoo подскажите, пожалуйста, проблему с висящим бесконечно UIActivityIndicator удалось решить удержанием сильной ссылки на AcquiringUISDK?

**Comment by razorkoo** [comment]
@grishamsc Да, проблему решить удалось

**Comment by romdevios** [comment]
@grishamsc у меня не решилась вот создаю на ините sdk и потом использую для оплаты с apple pay и без, но единственное что появляется это белая плашка с крутящейся activity.
 
<img width="667" alt="Screenshot 2020-11-06 at 23 32 48" src="https://user-images.githubusercontent.com/12981093/98412086-6231bd00-2088-11eb-949b-474931f71ebb.png">

<img width="545" alt="Screenshot 2020-11-06 at 23 33 32" src="https://user-images.githubusercontent.com/12981093/98412144-7d9cc800-2088-11eb-8783-a8c3791297fa.png">

**Comment by romdevios** [comment]
что за извращения, хоть ошибку покажите какую...

**Comment by grishamsc** [comment]
закрываю 🙂
