### ISSUE TITLE
Блокировка интерфейса

### ISSUE THREAD

**Issue by razorkoo** [TinkoffCreditSystems/AcquiringSdk_IOS#14]
Здравствуйте, подскажите, пожалуйста, по какой причине может происходить блокировка интерфейса после выполнения completion блока у сканера ( контроллер сканера закрывается, появляется клавиатура для ввода cvc кода, но в данный момент времени интерфейс уже не откликается ни на что). Если закомментировать данную строчку (https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/blob/3a465b14e1393cd53d67b3d00e649e82533a70bf/TinkoffASDKUI/TinkoffASDKUI/PopUpViewContoller.swift#L238), то блокировка интерфейса проходит.

**Comment by grishamsc** [comment]
@razorkoo Здравствуйте. Подскажите, пожалуйста, это происходит на симуляторе, на девайсе или на обоих сразу. И на какой версии iOS?

**Comment by razorkoo** [comment]
@grishamsc Это происходит на устройстве, версия iOS 14.1

**Comment by grishamsc** [comment]
@razorkoo 
спасибо. еще пара уточнений: 
- вы используете какой-то готовый сканер или самописное решение?
- `completion` в методе `presentScanner` вызывается на главном потоке?

**Comment by razorkoo** [comment]
@grishamsc Используем готовый сканер от Card.IO. Completion блок вызывается в главном потоке

**Comment by grishamsc** [comment]
@razorkoo 
исправлено в версии 2.1.3 🙂
