### ISSUE TITLE
Очистка навигационного стека

### ISSUE THREAD

**Issue by razorkoo** [TinkoffCreditSystems/AcquiringSdk_IOS#15]
Добрый вечер, столкнулись с такой проблемой, что после подтверждения оплаты через 3ds навигационный стек сразу же очищается до рут контроллера. Данная ошибка случается, если модальное окно с данными для оплаты разворачивается на полный экран, однако, если производить оплату, к примеру, через ApplePay, то после подтверждения оплаты навигационный стек чиститься только до того контроллера из которого была вызвана оплата. В нашей реализации это несколько критично.

**Comment by grishamsc** [comment]
Здравствуйте, посмотрим в ближайшее время.
Будем признательны, если схематически опишите иерархию viewController'ов.

**Comment by razorkoo** [comment]
Добрый день! Получается как-то так. Т.е при закрытии paymentView у нас вместо того, чтобы вернуться на OrderProcessingViewController, мы попадаем на BasketViewController. При использовании payWithApplePay мы возвращаемся на OrderProcessingViewController.
![Иерархия](https://user-images.githubusercontent.com/9390876/99243753-2af2a700-2812-11eb-9a70-107b438df6d3.png)

**Comment by grishamsc** [comment]
@razorkoo 
никак не получается воспроизвести поведение, о котором вы написали
уточните, пожалуйста, все же об очистке какого стека идет речь? насколько я вижу, в вашей схеме `BasketViewController` и `OrderProcessingViewController` не находятся в одном стеке, т.к. `BasketViewController` модально презентует `OrderProcessingViewController` через `presentViewController:`. 
и, если вас не затруднит, было бы здорово, если бы вы смогли прислать проект-пример, где воспроизведен флоу показа и где можно понаблюдать проблему. это очень поможет

**Comment by razorkoo** [comment]
> @razorkoo
> никак не получается воспроизвести поведение, о котором вы написали
> уточните, пожалуйста, все же об очистке какого стека идет речь? насколько я вижу, в вашей схеме `BasketViewController` и `OrderProcessingViewController` не находятся в одном стеке, т.к. `BasketViewController` модально презентует `OrderProcessingViewController` через `presentViewController:`.
> и, если вас не затруднит, было бы здорово, если бы вы смогли прислать проект-пример, где воспроизведен флоу показа и где можно понаблюдать проблему. это очень поможет

Там получается так, что при скрытии PaymentView по какой-то причине он тянет за собой OrderProcessingViewController и тем самым мы оказываемся в BasketViewController. К сожалению, тестовый проект предоставить не могу(

**Comment by volkoivan** [comment]
Подтверждаю наличие проблемы как описал ее автор

**Comment by grishamsc** [comment]
Удалось воспроизвести. Приложенная ранее схема не полностью отображает иерархию вью контроллеров, при котором воспроизводится проблема. Прикладываю более точную.
![1](https://user-images.githubusercontent.com/2726726/103309639-a6a55d80-4a26-11eb-862c-32333e46c119.png)

**Comment by grishamsc** [comment]
исправлено в версии 2.1.4 🙂
