### ISSUE TITLE
Валюта платежа

### ISSUE THREAD

**Issue by movch** [TinkoffCreditSystems/AcquiringSdk_IOS#18]
Здравствуйте,

Подскажите, а можно как-то задать валюту платежа? В документации (https://acdn.tinkoff.ru/static/acquiring/5fe98aaa-ec9c-48ff-bcfb-abc2b71d4ee2.pdf) в разделе "API Методы для работы с сервером" указано что в метод https://securepay.tinkoff.ru/v2/Init можно отдать параметр Currency, но я не вижу такого параметра в модели PaymentInitData.

**Comment by MaryAPc** [comment]
Здравствуйте, SDK поддерживает только рубли. При использовании методов на сервере, вы можете указать любую валюту, но списания будут в рублях
