### ISSUE TITLE
AcquiringUISDK.presentCardList

### ISSUE THREAD

**Issue by Akree** [TinkoffCreditSystems/AcquiringSdk_IOS#2]
**Здравствуйте.**
Хотелось бы некоторых уточнений ~~и возможно исправлений~~ по использованию данного метода.

1. При открытии экрана сохраненных карт с новым `customerId` отображается следующее: 
> <img src="https://user-images.githubusercontent.com/48877932/88289956-3af4f100-cd20-11ea-8b5b-71d5a50dedd6.png" width = 200>

Также при попытке добавить карту этому юзеру:  
> <img src="https://user-images.githubusercontent.com/48877932/88289966-3e887800-cd20-11ea-8681-32e4583d7035.png" width = 200>

2. Можно ли не показывать диалоговое окно как при успешном добавлении, так и при возникновении ошибки? 
Не думаю что конечному пользователю необходимо видеть `id` его карты (как в дефолтном сообщении).

3. И еще один вопрос, как отследить закрытие экрана сохраненных карт? 

Спасибо)

**Comment by slavabuv** [comment]
Добрый день! Про ошибку уже есть задача, ждем исправления.
Про диалоговое окно - сделаем доработку, показывать / не показывать и использовать либо из приложения либо из SDK.

**Comment by Akree** [comment]
2.0.1:
1. Cписок карт нового юзера отображается верно
2. Но при попытке добавить новую карту получаем все ту же ошибку "Внутренняя ошибка системы интернет эквайринга" 😿
