### ISSUE TITLE
Отсутствие инициализаторов для признака агента и данных о продавце (AgentData и SupplierInfo)

### ISSUE THREAD

**Issue by konstructor1** [TinkoffCreditSystems/AcquiringSdk_IOS#20]
Скажите пожалуйста, в прошлой версии ASDK данные чека, признаки агента и данные о продавце передавались в виде словарей типа [String: Any].
Теперь, в новой версии, для них выделили отдельные классы Receipt, AgentData и SupplierInfo, однако для AgentData и SupplierInfo из инициализаторов доступны и существуют только init(from decoder)..

**Comment by grishamsc** [comment]
исправлено в версии 2.1.3 🙂
