### ISSUE TITLE
Не приходят квитанции на электронную почту

### ISSUE THREAD

**Issue by gladkovao** [TinkoffCreditSystems/AcquiringSdk_IOS#21]
Здравствуйте. На указанную почту не приходят квитанции об оплате. При отладке в PaymentFinishRequestData sendEmail устанавливается true, но письма все равно нет. Посмотрите, пожалуйста.

**Comment by MaryAPc** [comment]
Здравствуйте! Вы заполняли email на экране оплаты, или передавали в SDK? Также нам помогли бы логи, в частности логи метода https://rest-api-test.tcsbank.ru/v2/FinishAuthorize

**Comment by gladkovao** [comment]
Email добавляю: 
viewConfigration.fields.append(AcquiringViewConfiguration.InfoFields.email(value: user.email, placeholder: "Отправить квитанцию по адресу")) 
Но даже если заполнить на экране, то письма тоже нет. 

Printing description of **requestData**:
▿ PaymentFinishRequestData
  - paymentId : 700000843292
  ▿ paymentSource : PaymentSourceData
    ▿ savedCard : 2 elements
      - cardId : "70000005241"
      ▿ cvv : Optional<String>
        - some : "111"
  ▿ sendEmail : Optional<Bool>
    - some : true
  ▿ infoEmail : Optional<String>
    - some : "gladkovao1994@mail.ru"
  - deviceInfo : nil
  - ipAddress : nil
  - threeDSVersion : nil
  - source : nil
  - route : nil

Printing description of **response**:
▿ Result<PaymentFinishResponse, Error>
  ▿ success : PaymentFinishResponse
    - success : true
    - errorCode : 0
    - errorMessage : nil
    - errorDetails : nil
    ▿ terminalKey : Optional<String>
      - some : "1541700075694DEMO"
    - paymentStatus : TinkoffASDKCore.PaymentStatus.confirmed
    ▿ responseStatus : PaymentFinishResponseStatus
      ▿ done : PaymentStatusResponse
        - success : true
        - errorCode : 0
        - errorMessage : nil
        - errorDetails : nil
        ▿ terminalKey : Optional<String>
          - some : "1541700075694DEMO"
        - orderId : "6201"
        - paymentId : 700000843292
        - amount : 42.75
        - status : TinkoffASDKCore.PaymentStatus.confirmed

**Comment by MaryAPc** [comment]
На тестовом или боевом окружении (serverEnvironment) совершали операцию?

**Comment by gladkovao** [comment]
AcquiringSdkEnvironment.test

**Comment by memphisprog** [comment]
Добрый день.

Есть ли какая либо информация по данной проблеме?

Возможно мы делаем что то не так?

**Comment by MaryAPc** [comment]
@memphisprog @gladkovao Передала коллегам с бека проблему, разбираются. Как будут новости я вам сообщу

**Comment by memphisprog** [comment]
Добрый день.

Что то прояснилось по задачке?

**Comment by MaryAPc** [comment]
Задача у коллег сейчас в работе

**Comment by MaryAPc** [comment]
@memphisprog @gladkovao мы выяснили, что сейчас квитанции отправляются только на прод контуре https://securepay.tinkoff.ru 
если включен тестовый контур https://rest-api-test.tinkoff.ru, то квитанции на почту приходить не будут

**Comment by memphisprog** [comment]
Добрый день

Спасибо

Мы уже поняли что на бою летает

Думаю задачу можно закрыть
