### ISSUE TITLE
Легкая версия для интеграции в App Clips

### ISSUE THREAD

**Issue by illabo** [TinkoffCreditSystems/AcquiringSdk_IOS#3]
Есть ли в планах создание легкой версии SDK для iOS 14 для интеграции в App Clips?

**Comment by slavabuv** [comment]
Легкой версии не планировалось, тк нет лишнего и не нужного функционала.
Текущая версия с тестовым примером ~5 Мб.
Планируется провести оптимизацию чтобы уменьшить текущий размер.

**Comment by illabo** [comment]
Ок, понял. Но у App Clips лимит 10 Мб, каждый байтик на счету. :)
