### ISSUE TITLE
Инициализация информации о товаре

### ISSUE THREAD

**Issue by gladkovao** [TinkoffCreditSystems/AcquiringSdk_IOS#31]
Здравствуйте. 
При оплате очень редко, но появляется ошибка "Сумма всех позиций в чеке должна ровняться сумме всех видов оплаты". В PaymentInitData сумма передается в копейках. Можно добавить метод инициализации для struct Item в AcquiringModels.swift, чтобы в параметрах тоже передавать суммы в копейках(Int64)?

**Comment by MaryAPc** [comment]
Здравствуйте! Да, задача на это есть, в одном из ближайших релизов метод появится

**Comment by gladkovao** [comment]
Спасибо

**Comment by gladkovao** [comment]
А когда ближайший релиз? 
Проблемы при оплате с копейками. 
Судя по тестам, мы ни через строку, ни через Double не можем инициализировать NSDecimalNumber, чтобы не потерять в точности  
<img width="1086" alt="Снимок экрана 2021-01-14 в 20 16 07" src="https://user-images.githubusercontent.com/45929388/104595814-b1f2bd00-56a5-11eb-8f71-6933c697756e.png">

**Comment by memphisprog** [comment]
Добрый день!

Очень актуальная задача, когда ждать релиза нового?

Или мы как то можем это обойти и решить нашу проблему?

**Comment by grishamsc** [comment]
@gladkovao @memphisprog 
в версии 2.1.5 добавлен метод инициализации структуры Item, принимающий price и amount в копейках.
