### ISSUE TITLE
Init на стороне сервера

### ISSUE THREAD

**Issue by itlogic** [TinkoffCreditSystems/AcquiringSdk_IOS#5]
Бизнес логика нашего проекта подразумевает Вызов Init и последующую проверку статуса по PaymentID на стороне бэка. Есть ли возможность сделать вызов presentPaymentView с передачей уже существующего PaymentID ??

В Android SDK это реализовано:

```
tinkoffAcquiring.openPaymentScreen(this, createPaymentOptions(), PAYMENT_REQUEST_CODE, SelectCardAndPayState(paymentId))
```

**Comment by itlogic** [comment]
??????????????

**Comment by MaryAPc** [comment]
Здравствуйте, извините за долгий ответ, сейчас у нас сменился разработчик ios sdk, сейчас разбираются есть ли реализованный такой функционал, и если его нет, то в одном из ближайших релизов сделают

**Comment by grishamsc** [comment]
Добавили такую возможность в версии 2.1.1

Передать paymentId при запуске оплаты можно таким образом:
```
let paymentId = 00000000
let acquiringConfiguration = AcquiringConfiguration(paymentStage: .paymentId(paymentId))
sdk.presentPaymentView(on: self,
                       paymentData: paymentData,
                       configuration: viewConfiguration,
                       acquiringConfiguration: acquiringConfiguration) { _ in }
```
