### ISSUE TITLE
Краш на экране списка карт

### ISSUE THREAD

**Issue by Megaman63** [TinkoffCreditSystems/AcquiringSdk_IOS#6]
<img width="521" alt="Screenshot 2020-10-10 at 10 44 53" src="https://user-images.githubusercontent.com/10582641/95649357-c8590d80-0ae5-11eb-8e2a-4b657c49ab26.png">
На экране списка карт можно попытать удалить плейсхолдер и получишь в итоге краш

**Comment by MaryAPc** [comment]
Спасибо за репорт, исправим в следующем релизе

**Comment by grishamsc** [comment]
@Megaman63 
исправлено в версии 2.1.0
