### ISSUE TITLE
Почему orderId имеет тип Int64?

### ISSUE THREAD

**Issue by Dorofeev** [TinkoffCreditSystems/AcquiringSdk_IOS#7]
Почему при инициализация платежа, номер заказа стало необходимым иметь в формате Int64? 
В частности в [PaymentInitData](https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/blob/b4dfe27e36d428774977a8f98f576fdb66de63fc/TinkoffASDKCore/TinkoffASDKCore/PaymentInitRequest.swift#L30)

Ведь в [документации АПИ](https://oplata.tinkoff.ru/develop/api/payments/init-request/) он указан как строка. И в старой версии сдк тоже была строка. Это блокирует нам переход на новую версию сдк, так как в нашей системе, id заказа это строка.

**Comment by MaryAPc** [comment]
Создали задачу на исправление, в следующем релизе заменим на строку

**Comment by Alex009** [comment]
> Создали задачу на исправление, в следующем релизе заменим на строку

Возможен ли workaround на данный момент? Или следующий релиз можно ожидать в скором времени? Есть ли ориентир по срокам?

**Comment by MaryAPc** [comment]
Я уточню у разработчиков iOS и сориентирую вас

**Comment by grishamsc** [comment]
@Dorofeev @Alex009 
исправлено в версии 2.1.0
