### ISSUE TITLE
Оплата на тестовом терминале возвращает НЕВЕРНЫЕ ПАРАМЕТРЫ, НЕВЕРНЫЙ НОМЕР КАРТЫ, ошибка 9999

### ISSUE THREAD

**Issue by roman-mityukov** [TinkoffCreditSystems/AcquiringSdk_IOS#9]
Здравствуйте
В ASDKSample поменял в StageTestData значения констант на значения своего тестового терминала
`/// Открытый ключ для шифрования карточных данных (номер карты, срок дейсвия и секретный код)
	public static let testPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv5yse9ka3ZQE0feuGtemYv3IqOlLck8zHUM7lTr0za6lXTszRSXfUO7jMb+L5C7e2QNFs+7sIX2OQJ6a+HG8kr+jwJ4tS3cVsWtd9NXpsU40PE4MeNr5RqiNXjcDxA+L4OsEm/BlyFOEOh2epGyYUd5/iO3OiQFRNicomT2saQYAeqIwuELPs1XpLk9HLx5qPbm8fRrQhjeUD5TLO8b+4yCnObe8vy/BMUwBfq+ieWADIjwWCMp2KTpMGLz48qnaD9kdrYJ0iyHqzb2mkDhdIzkim24A3lWoYitJCBrrB2xM05sm9+OdCI1f7nPNJbl5URHobSwR94IRGT7CJcUjvwIDAQAB"
	
	/// Уникальный идентификатор терминала, выдается Продавцу Банком на каждый магазин.
	public static let terminalKey = "1584508248174DEMO"
	
	/// Пароль от терминала
	public static let terminalPassword = "y9qfbavhebmp85k5"
	
	/// Идентификатор клиента в системе продавца. Например, для этого идентификатора будут сохраняться список карт.
	public static let customerKey = "f768d420-133c-11eb-b341-8b3d07d3e0a6"`

установил server: AcquiringSdkEnvironment.test

Больше в коде ничего не менял, оплата возвращает НЕВЕРНЫЕ ПАРАМЕТРЫ, НЕВЕРНЫЙ НОМЕР КАРТЫ, ошибка 9999

На андроид платеж с этими же данными терминала и customerKey завершается успешно

**Comment by roman-mityukov** [comment]
Логи запросов

🛫 Start POST request: https://rest-api-test.tcsbank.ru/v2/GetCardList, with paramaters: ["Token": "259bf8f71a77003ad3a37d0bb6b1e6aeb960a6eacbd9388cc0aec8be1a071b6b", "CustomerKey": f768d420-133c-11eb-b341-8b3d07d3e0a6, "TerminalKey": "1584508248174DEMO"]
[ASDK ->]: on <NSThread: 0x28353f640>{number = 6, name = (null)}, in NetworkTransport.swift, func send(operation:responseDelegate:completionHandler:), at line: 229 do:
🛬 End request: https://rest-api-test.tcsbank.ru/v2/GetCardList, with response data:
{"Success":false,"ErrorCode":"7","Message":"Неверный статус покупателя.","Details":"Покупатель не найден.","CustomerKey":"f768d420-133c-11eb-b341-8b3d07d3e0a6"}
[ASDK ->]: on main thread, in NetworkTransport.swift, func createRequest(for:), at line: 92 do:
🛫 Start POST request: https://rest-api-test.tcsbank.ru/v2/GetCardList, with paramaters: ["TerminalKey": "1584508248174DEMO", "CustomerKey": f768d420-133c-11eb-b341-8b3d07d3e0a6, "Token": "259bf8f71a77003ad3a37d0bb6b1e6aeb960a6eacbd9388cc0aec8be1a071b6b"]
[ASDK ->]: on <NSThread: 0x28353f640>{number = 6, name = (null)}, in NetworkTransport.swift, func send(operation:responseDelegate:completionHandler:), at line: 229 do:
🛬 End request: https://rest-api-test.tcsbank.ru/v2/GetCardList, with response data:
{"Success":false,"ErrorCode":"7","Message":"Неверный статус покупателя.","Details":"Покупатель не найден.","CustomerKey":"f768d420-133c-11eb-b341-8b3d07d3e0a6"}
[ASDK ->]: on main thread, in NetworkTransport.swift, func createRequest(for:), at line: 92 do:
🛫 Start POST request: https://rest-api-test.tcsbank.ru/v2/Init, with paramaters: ["Description": Краткое описние товара, "Amount": 10000, "Token": "536dd4dedbc82aa0ec7a66f70bdd58087c82c20bc3b1634d9074cf0e29e33e9e", "CustomerKey": f768d420-133c-11eb-b341-8b3d07d3e0a6, "Receipt": {
    Items =     (
                {
            Amount = 10000;
            Name = "\U0428\U0430\U043d\U0442\U0430\U0440\U0430\U043c - 2. \U0422\U0435\U043d\U044c \U0433\U043e\U0440\U044b";
            Price = 10000;
            Quantity = 1;
            Tax = vat10;
        }
    );
    Phone = "+79876543210";
    Taxation = osn;
}, "TerminalKey": "1584508248174DEMO", "OrderId": 3770773982]
[ASDK ->]: on <NSThread: 0x28351e980>{number = 5, name = (null)}, in NetworkTransport.swift, func send(operation:responseDelegate:completionHandler:), at line: 229 do:
🛬 End request: https://rest-api-test.tcsbank.ru/v2/Init, with response data:
{"Success":true,"ErrorCode":"0","TerminalKey":"1584508248174DEMO","Status":"NEW","PaymentId":"700000381830","OrderId":"3770773982","Amount":10000,"PaymentURL":"https://rest-api-test.tinkoff.ru/new/tk7VPdND"}
2020-10-21 12:44:10.620577+0700 ASDKSample[4339:2344786] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
2020-10-21 12:44:18.566268+0700 ASDKSample[4339:2344786] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
2020-10-21 12:44:20.703653+0700 ASDKSample[4339:2344786] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
[ASDK ->]: on main thread, in NetworkTransport.swift, func createRequest(for:), at line: 92 do:
🛫 Start POST request: https://rest-api-test.tcsbank.ru/v2/Check3dsVersion, with paramaters: ["PaymentId": 700000381830, "CardData": "RmjQ/g9qQOb06/O2rmdSQbMwDuEEc29SrBXj5oqlk4VnhBR4Uz+0Cgq2GuYRwbzy33xb41p0B93yIVI24Hi3befDLzV0QyVTzI07ymnYNR+w/h3LH6VuNdUh6bj/QghWVyFa8jzSiPk1wOLq0k6GsjzjIFNJqztLei7S2SKEITVoZG6iFaYo3mOtiN10wmiG5PkkorrlXV7juaR64FsIID+GXQ7/qEA4M9k0D/NVh99IRKSFmuk+avku9VdQk3j87YWPpd/l2RS/yVcju9TFfPGkaipW9/jTOoLngDhr1/4PfI42zQriVyP5ll20K58EJvsBGT1itTwcarGjl0qMig==", "Token": "1d73d6dd4455441825c9843d6f1f74a9cfb4d1393213b0960ec961b2fdf37b51", "TerminalKey": "1584508248174DEMO"]
[ASDK ->]: on <NSThread: 0x28353f640>{number = 6, name = (null)}, in NetworkTransport.swift, func send(operation:responseDelegate:completionHandler:), at line: 229 do:
🛬 End request: https://rest-api-test.tcsbank.ru/v2/Check3dsVersion, with response data:
{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Неверный номер карты"}
2020-10-21 12:44:23.488138+0700 ASDKSample[4339:2344786] [strings] ERROR: Неверные параметры. Неверный номер карты not found in table Error of bundle CFBundle 0x130313a10 </System/Library/Frameworks/CoreFoundation.framework> (framework, loaded)

**Comment by MaryAPc** [comment]
Здравствуйте! Попробовала провести транзакцию с вашими данными терминала на андроид, получаю такую же ошибку. Как давно вы тестировали это на андроид? После этого вам не меняли настройки терминала?

**Comment by roman-mityukov** [comment]
Похоже, что у меня ошибка - на андроид у меня был AcquiringSdk.isDeveloperMode = false, т.е. использовалось прод окружение. С ним тестовые платежи для тестового терминала в личном кабинете проходят успешно. И проверил на iOS с server: AcquiringSdkEnvironment.prod - тоже успешно.

Нужно использовать prod environment при тестировании платежей на тестовом терминале в личном кабинете?

![Screenshot 2020-10-21 at 15 11 26](https://user-images.githubusercontent.com/3109589/96692381-2a502780-13b0-11eb-84dd-fe889adb3dce.png)

**Comment by MaryAPc** [comment]
В данном случае выполняется тест с проверкой 3DS. В тестовом окружении этот кейс можно проверить на прод терминале (без DEMO) и на реальной карте (в тестовом окружении деньги не спишутся).
Или лучше проверять сразу на прод окружении с прод терминалом

**Comment by roman-mityukov** [comment]
Ок, понял, спасибо
